//storeConstants.js

export const SET_PAGE = 'SET_PAGE';
export const CHANGE_VIEW = 'CHANGE_VIEW';
export const CHANGE_DISPLAY = 'CHANGE_DISPLAY';
export const SET_INITIAL_VIEW = 'SET_INITIAL_VIEW';

export const CHANGE_CHIT_DISPLAYED = 'CHANGE_CHIT_DISPLAYED';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
 

// export const SET_INITIAL_CHITS = 'SET_INITIAL_CHITS';


// export const CHANGE_MONTH = 'CHANGE_MONTH';
 
// export const CHANGE_DISPLAY_PERSON = 'CHANGE_DISPLAY_PERSON';
// export const CHANGE_DISPLAY_CATEGORY = 'CHANGE_DISPLAY_CATEGORY';
// export const CHANGE_DISPLAY_CHIT_TYPE = 'CHANGE_DISPLAY_CHIT_TYPE';




// export const SHOW_ACCORDION_DETAIL = 'SHOW_ACCORDION_DETAIL';
// export const CLOSE_ACCORDION_DETAIL = 'CLOSE_ACCORDION_DETAIL';

// export const SET_INITIAL_PAGE = 'SET_INITIAL_PAGE';
// export const UPDATE_CHIT_FORM_DATA = 'UPDATE_CHIT_FORM_DATA';
// export const CHANGE_DISPLAY_ARRAY = 'CHANGE_DISPLAY_ARRAY';


