//storeConstants.js

export const SET_PAGE = 'SET_PAGE';
export const OPEN_CLOSE_SIDE_PANEL = 'OPEN_CLOSE_SIDE_PANEL';
export const SHOW_SPOTLIGHT = 'SHOW_SPOTLIGHT';
export const CLOSE_SPOTLIGHT = 'CLOSE_SPOTLIGHT';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const CHANGE_DISPLAY_SPOTLIGHT ='CHANGE_DISPLAY_SPOTLIGHT'
export const OPEN_SPOTLIGHT_PAGE = 'OPEN_SPOTLIGHT_PAGE'
export const CLOSE_SPOTLIGHT_PAGE = 'CLOSE_SPOTLIGHT_PAGE'
export const CHANGE_DISPLAY = 'CHANGE_DISPLAY';




